version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - messaging-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: messaging-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - messaging-network

  db:
    image: mysql:8.0
    container_name: messaging-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: messaging_system
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: messaging_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - messaging-network

  redis:
    image: redis:alpine
    container_name: messaging-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - messaging-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messaging-queue
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    networks:
      - messaging-network
    depends_on:
      - db
      - redis

volumes:
  dbdata:
    driver: local

networks:
  messaging-network:
    driver: bridge
